<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_info.proto

namespace GPBMetadata;

class LoginInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Á
login_info.protoBrawn.Protobuf"p
	LoginInfo
name (	
version (
preInstallHook (	
postInstallHook (	
versionName (	B#
com.android.brawnBProtoLoginInfobproto3'
        , true);

        static::$is_initialized = true;
    }
}

