<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserReg.proto

namespace GPBMetadata;

class ReqUserReg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '

ReqUserReg.protoBrawn.Protobuf">

ReqUserReg
	isSuccess (
errMsg (	
token (	B$
com.android.brawnBReqUserRegProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

