<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResUserReg.proto

namespace GPBMetadata;

class ResUserReg
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
…
ResUserReg.protoBrawn.Protobuf"3

ResUserReg
reg_card (	
reg_machine (	B$
com.android.brawnBResUserRegProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

