<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_info.proto

namespace Brawn\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Brawn.Protobuf.LoginInfo</code>
 */
class LoginInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Package Name
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Version Number
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     */
    protected $version = 0;
    /**
     * Pre Install Hook
     *
     * Generated from protobuf field <code>string preInstallHook = 3;</code>
     */
    protected $preInstallHook = '';
    /**
     * Post Install Hook
     *
     * Generated from protobuf field <code>string postInstallHook = 4;</code>
     */
    protected $postInstallHook = '';
    /**
     * Version Name
     *
     * Generated from protobuf field <code>string versionName = 5;</code>
     */
    protected $versionName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Package Name
     *     @type int|string $version
     *           Version Number
     *     @type string $preInstallHook
     *           Pre Install Hook
     *     @type string $postInstallHook
     *           Post Install Hook
     *     @type string $versionName
     *           Version Name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LoginInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Package Name
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Package Name
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Version Number
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Version Number
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Pre Install Hook
     *
     * Generated from protobuf field <code>string preInstallHook = 3;</code>
     * @return string
     */
    public function getPreInstallHook()
    {
        return $this->preInstallHook;
    }

    /**
     * Pre Install Hook
     *
     * Generated from protobuf field <code>string preInstallHook = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPreInstallHook($var)
    {
        GPBUtil::checkString($var, True);
        $this->preInstallHook = $var;

        return $this;
    }

    /**
     * Post Install Hook
     *
     * Generated from protobuf field <code>string postInstallHook = 4;</code>
     * @return string
     */
    public function getPostInstallHook()
    {
        return $this->postInstallHook;
    }

    /**
     * Post Install Hook
     *
     * Generated from protobuf field <code>string postInstallHook = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPostInstallHook($var)
    {
        GPBUtil::checkString($var, True);
        $this->postInstallHook = $var;

        return $this;
    }

    /**
     * Version Name
     *
     * Generated from protobuf field <code>string versionName = 5;</code>
     * @return string
     */
    public function getVersionName()
    {
        return $this->versionName;
    }

    /**
     * Version Name
     *
     * Generated from protobuf field <code>string versionName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVersionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->versionName = $var;

        return $this;
    }

}

