<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUserReg.proto

namespace Brawn\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Brawn.Protobuf.ReqUserReg</code>
 */
class ReqUserReg extends \Google\Protobuf\Internal\Message
{
    /**
     * 卡密
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     */
    protected $isSuccess = false;
    /**
     * 机器码
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     */
    protected $errMsg = '';
    /**
     * 机器码
     *
     * Generated from protobuf field <code>string token = 3;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isSuccess
     *           卡密
     *     @type string $errMsg
     *           机器码
     *     @type string $token
     *           机器码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ReqUserReg::initOnce();
        parent::__construct($data);
    }

    /**
     * 卡密
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     * @return bool
     */
    public function getIsSuccess()
    {
        return $this->isSuccess;
    }

    /**
     * 卡密
     *
     * Generated from protobuf field <code>bool isSuccess = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->isSuccess = $var;

        return $this;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->errMsg;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->errMsg = $var;

        return $this;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string token = 3;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

