<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResUserReg.proto

namespace Brawn\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Brawn.Protobuf.ResUserReg</code>
 */
class ResUserReg extends \Google\Protobuf\Internal\Message
{
    /**
     * 卡密
     *
     * Generated from protobuf field <code>string reg_card = 1;</code>
     */
    protected $reg_card = '';
    /**
     * 机器码
     *
     * Generated from protobuf field <code>string reg_machine = 2;</code>
     */
    protected $reg_machine = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reg_card
     *           卡密
     *     @type string $reg_machine
     *           机器码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResUserReg::initOnce();
        parent::__construct($data);
    }

    /**
     * 卡密
     *
     * Generated from protobuf field <code>string reg_card = 1;</code>
     * @return string
     */
    public function getRegCard()
    {
        return $this->reg_card;
    }

    /**
     * 卡密
     *
     * Generated from protobuf field <code>string reg_card = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->reg_card = $var;

        return $this;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string reg_machine = 2;</code>
     * @return string
     */
    public function getRegMachine()
    {
        return $this->reg_machine;
    }

    /**
     * 机器码
     *
     * Generated from protobuf field <code>string reg_machine = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegMachine($var)
    {
        GPBUtil::checkString($var, True);
        $this->reg_machine = $var;

        return $this;
    }

}

